apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-runtime-app" .Cluster.ObjectMeta.Name}}
  namespace: argocd
spec:
  project: {{.Cluster.ObjectMeta.Name}}-runtime-project
  source:
    path: runtimes/{{.Cluster.ObjectMeta.Name}}-runtime/production
    repoURL: {{.Repo.TenantRepoURL}}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
