{{- $default := "" -}}
{{- if ne .Cert nil -}}
    {{- $default = .Cert.Default -}}
{{- end -}}
apiVersion: v1
data:
  ca.crt: {{encodeToString $default}}
kind: Secret
metadata:
  name: idp-ca-secret
  namespace: oauth2-proxy
