apiVersion: v1
kind: ConfigMap
metadata:
  name: nautes-configs
  namespace: {{.NautesConfigs.Namespace}}
data:
  config: |
    git:
      addr: "{{.GitConfigs.Addr}}"
      defaultDeployKeyType: "{{.GitConfigs.DefaultDeployKeyType}}"
      gitType: {{.GitConfigs.GitType}}
    secret:
      vault:
        mountPath: "{{.Cluster.ObjectMeta.Name}}"
        addr: "{{.SecretConfigs.Vault.Addr}}"
        CABundle: |
{{- range $line := split .SecretConfigs.Vault.CABundle "\n" }}
          {{ $line | html }}
{{- end }}
