apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../nautes/overlays/runtime
- cm-nautes.yaml
{{- if eq .Cluster.Spec.ClusterType "physical"}}
- rbac-vault.yaml
{{end -}}