apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runtime-initial-appset
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          cluster.nautes.io/usage: worker
  template:
    metadata:
      name: '{{"{{name}}-runtime-initial"}}'
      namespace: argocd
    spec:
      project: {{.NautesConfigs.TenantName}}
      source:
        repoURL: {{.Repo.TenantRepoURL}}
        targetRevision: HEAD
        path: runtimes/{{printf "%s" "{{name}}-runtime"}}/initial/overlays/production
      destination:
        server: '{{"{{server}}"}}'
        namespace: {{.NautesConfigs.Namespace}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true              
        syncOptions:
          - CreateNamespace=true
