{{- $data := "" -}}
{{- if ne .Cert nil -}}
    {{- $data = .Cert.Gitlab -}}
{{- end -}}
---
apiVersion: v1
data:
  {{getDomain .GitConfigs.Addr}}: |-
  {{- range $line := split $data "\n" }}
    {{ $line | html }}
  {{- end }}
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
