{{- $data := getDeploymentServer . }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cm
data:
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
  url: {{$data.Argocd.URL}}
  dex.config: |
    connectors:
      - type: oidc
        id: dex
        name: Dex
        config:
          issuer: {{.OauthConfigs.Issuer}}
          clientID: {{.OauthConfigs.ClientID}}
          clientSecret: {{.OauthConfigs.ClientSecret}}
          insecureEnableGroups: true
          scopes:
          - "openid"
          - "profile"
          - "email"
          - "groups"
          getUserInfo: true
