---
apiVersion: v1
data:
  {{getDomain .GitConfigs.Addr}}: |-
  {{- range $line := split .CaBundleList.Gitlab "\n" }}
    {{ $line | html }}
  {{- end }}
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
