{{- $data := "" -}}
{{- if ne .Cert nil -}}
    {{- $data = .Cert.Default -}}
{{- end -}}
apiVersion: v1
data:
  ca-certs-Private-DEX.pem: {{encodeToString $data}}
kind: Secret
metadata:
  name: idp-ca-secret
