apiVersion: v1
kind: Service
metadata:
  name:  {{printf "svc-%s" .Cluster.Name}}
  namespace: {{.Cluster.Name}}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: {{.Vcluster | getVclusterHttpsNodePort}}
  selector:
    app: vcluster
  sessionAffinity: None
  type: NodePort