{{- $data := "" -}}
{{- if ne .Cert nil -}}
    {{- $data = .Cert.Default -}}
{{- end -}}
apiVersion: v1
data:
  ca.crt: {{encodeToString $data}}
kind: Secret
metadata:
  name: idp-ca-secret
  namespace: oauth2-proxy
