{{- $hostClusterName := .Cluster.ObjectMeta.Name -}}
{{- $data := getGatewayServer . -}}
{{- range $data.Traefik.Middlewares -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-{{.OAuth.Name}}
  namespace: traefik
spec:
  chain:
    middlewares:
    - name: oauth-errors-{{.Errors.Name}}
    - name: oauth-forward
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors-{{.Errors.Name}}
  namespace: traefik
spec:
  errors:
    status:
      - "401"
    service:
      name: {{$hostClusterName}}-oauth2-proxy
      namespace: oauth2-proxy
      port: 80
    query: {{printf "/oauth2/sign_in?rd=%s" .Errors.URL}}
{{- end -}}

