apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: {{.Runtime.ArgocdConfig.Project}}
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.7
    helm:
      values: |-
        extraVolumes:
          - name: etc-ssl-certs
            secret:
              secretName: ca
        extraVolumeMounts:
          - name: etc-ssl-certs
            mountPath: /etc/ssl/certs/ca.crt
            subPath: ca.crt
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
