{{- $data := getOauthProxyServer .}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: {{.Cluster.ObjectMeta.Name}}-runtime-project
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 6.12.0
    helm:
      values: |-
        config:
          clientID: {{.OauthConfigs.ClientID}}
          clientSecret: {{.OauthConfigs.ClientSecret}}

        extraArgs:
          provider: "oidc"
          provider-display-name: "Dex"
          whitelist-domain: "{{$data.OAuth2Proxy.WhitelistDomain}}"
          cookie-secure: "true"
          cookie-domain: "{{printf ".%s" .Cluster.Spec.PrimaryDomain}}"
          redirect-url: {{ $data.OAuth2Proxy.Redirect }}
          cookie-secret: "{{randomString 32}}"
          oidc-issuer-url: "{{.OauthConfigs.Issuer}}"
          scope: "openid profile email groups"
          email-domain: "*"
          skip-provider-button: "false"
          set-authorization-header: "true"

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
          tls:
            - hosts:
                - {{$data.OAuth2Proxy.Hosts}}
          path: /
          pathType: ImplementationSpecific
          hosts:
            - {{$data.OAuth2Proxy.Hosts}}

        extraVolumes:
          - name: ca-bundle-cert
            secret:
              secretName: idp-ca-secret

        extraVolumeMounts:
          - mountPath: /etc/ssl/certs/
            name: ca-bundle-cert
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
