apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: {{.Cluster.ObjectMeta.Name}}-runtime-project
  source:
    path: runtimes/{{.Cluster.ObjectMeta.Name}}-runtime/tekton/overlays/production
    repoURL: {{.Repo.TenantRepoURL}}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
