{{- $data := getGatewayServer .}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: {{.Cluster.ObjectMeta.Name}}-runtime-project
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: v10.22.0
    helm:
      values: |-
        service:
          type: NodePort
          annotations:
            "cluster-operator.nautes.io/http-entrypoint": "web"
            "cluster-operator.nautes.io/https-entrypoint": "websecure"
          labels:
            "resource.nautes.io/Usage": "Entrypoint"      
        ports:
          traefik:
            port: 9000
          web:
            nodePort: {{$data.Traefik.HttpNodePort}}
          websecure:
            nodePort: {{$data.Traefik.HttpsNodePort}}
            tls:
              enabled: true
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
          kubernetesCRD:
            allowCrossNamespace: true
            
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

