{{- if eq .Cluster.Spec.ClusterType "physical" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-oauth2-proxy-resources" .Cluster.ObjectMeta.Name}}
  namespace: argocd
spec:
  project: {{.NautesConfigs.TenantName}}
  source:
    path: host-clusters/{{.Cluster.ObjectMeta.Name}}/oauth2-proxy/overlays/production
    repoURL: {{.Repo.TenantRepoURL}}
    targetRevision: HEAD
  destination:
    server: {{.Cluster.Spec.ApiServer}}
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end}}
