{{- if eq .Cluster.Spec.Usage "host" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  {{printf "%s-traefik-resources" .Cluster.ObjectMeta.Name}}
  namespace: argocd
spec:
  project: {{.NautesConfigs.TenantName}}
  source:
    path: host-clusters/{{.Cluster.ObjectMeta.Name}}/traefik/overlays/production
    repoURL: {{.Repo.TenantRepoURL}}
    targetRevision: HEAD
  destination:
    server: {{.Cluster.Spec.ApiServer}}
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end}}