{{- $hostClusterName := .Cluster.ObjectMeta.Name -}}
{{- $vclusters := getVclusterByHostCluserName . $hostClusterName -}}
{{- if gt (len $vclusters) 0 -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{printf "%s-vcluster-appset" $hostClusterName}}
spec:
  generators:
  - list:
      elements:
      {{- range .Clusters }}
        {{- if eq .Spec.HostCluster  $hostClusterName }}
        - cluster: {{.ObjectMeta.Name }}
        {{- end}}
      {{- end}}      
  template:
    metadata:
      name: '{{"{{cluster}}"}}'
    spec:
      project: {{.NautesConfigs.TenantName}}
      source:
        path: host-clusters/{{$hostClusterName}}/vclusters/{{printf "%s" "{{cluster}}"}}
        repoURL: {{.Repo.TenantRepoURL}}
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
{{- end -}}