apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  {{printf "%s-vcluster-initial" .Cluster.ObjectMeta.Name}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: {{.NautesConfigs.TenantName}}
  source:
    path: host-clusters/{{.HostCluster.ObjectMeta.Name}}/vclusters/{{.Cluster.ObjectMeta.Name}}/vcluster-initial
    repoURL: {{.Repo.TenantRepoURL}}
    targetRevision: HEAD
  destination:
    server: {{.HostCluster.Spec.ApiServer}}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
