{{- $data := "" -}}
{{- if ne .Cert nil -}}
    {{- $data = .Cert.Default -}}
{{- end -}}
apiVersion: v1
data:
  ca.crt: |
  {{- range $line := split $data "\n" }}
    {{ $line | html }}
  {{- end }}
kind: ConfigMap
metadata:
  name: ca-certificates
  namespace: argo-events
